config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  get 'messages/show'

  get 'messages/edit'

  get 'messages/update'

  get 'messages/destroy'


  root to: 'visitors#index'
  devise_for :users
  resources :users
  resources :dogs
  resources :messages
end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  age         :integer
#  breed       :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#

class Dog < ActiveRecord::Base
	belongs_to :user
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  to         :integer
#  from       :integer
#  date       :string(255)
#  type       :string(255)
#  message    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Message < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  which                  :integer
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: {:message => "No name given"}
  validates :name, uniqueness: {:message => "Already exists"}

  has_many :dogs
  has_many :messages
  has_many :reviews
  belongs_to :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	def new
	end
	def create
		@dog = Dog.new(dog_params)
		@dog.user_id = current_user.id
		if @dog.save
			current_user.which = 1
			@current_user.save
			redirect_to current_user
		else
			flash[:error] = @dog.errors.full_messages.to_sentence
			render 'new'
		end
	end
	def show
		@dog = Dog.find(params[:id])
	end
	def dog_params
		params.require(:dog).permit(:name, :age, :breed)
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
   
  end

  def create
    @message = Message.new(message_params)
    @message.to = message_params[:to]
    @message.date = message_params[:date]
    @message.from = current_user.id
    @message.save
    redirect_to user_path(message_params[:to])
    
  end

  def show
  end

  private 

  def message_params
    params.require(:message).permit(:message, :to, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/dogs/new.html.erb
<div id="dog-form">

<%= simple_form_for Dog.new, url: { action: 'create' } do |f| %>
  Name: <%= f.input :name %>
  Age: <%= f.input :age %>
  Breed: <%= f.input :breed %>
  Description: <%= f.input :description %>
  <%= f.submit "Create" %>
  <% end %>

</div>

app/views/dogs/show.html.erb
<div class="user-prof">

<div class="circle-img">
		<%= image_tag "dog_prof.png", :style => "width:150px; height: 150px; opacity:.5;" %>
	</div>

<div class="dog-bio">

	<h3><%= @dog.name if @dog.name %></h3>
<p>Owner: <%= User.find(@dog.user_id).name %> </p>
<p>Breed: <%= @dog.breed if @dog.breed %></p>
<p>Age: <%= @dog.age if @dog.age %></p>
<p>Description: <%= @dog.description if @dog.description %></p>

<button type="button" class="btn btn-primary"><%= link_to ' Go back to Owner', user_path(User.find(@dog.user_id)), :style => "color:#fff;"%>
</div>



</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Messages', messages_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dog App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<td><%= link_to message.from, message %></td>
<td><%= link_to message.message, message %></td>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/destroy.html.erb
<h1>Messages#destroy</h1>
<p>Find me in app/views/messages/destroy.html.erb</p>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
    <h3>Messages</h3>
      <table class="table">
        <tbody>
          <% @messages.each do |message| %>

            <tr>
              <% if message.to == current_user.id %>
                <div class="message-box">
                  <div id="from">
                    From: <%= User.find(message.from).name %>
                    <div id="date"> 
                    <%= message.date %>
                    </div>
                  </div>

                  <div id="message">
                    <%= message.message %>
                  </div>
                    <button type="button" class="btn btn-primary"><%= link_to ' Reply', user_path(message.from), :style => "color:#fff;"%></button>
                </div>
              <%end%>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/messages/new.html.erb
<h1>Messages#new</h1>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>








	
	

app/views/messages/update.html.erb
<h1>Messages#update</h1>
<p>Find me in app/views/messages/update.html.erb</p>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb


<div class="user-prof">

	<div class="bio-top">
		<div id="username">
	<h2><%= @user.name if @user.name %></h2>
</div>

<div class="circle-img">
		<%= image_tag "prof.png", :style => "width:150px; height: 150px; opacity:.5;" %>
	</div>


<div id="user-bio"> 
	<% if @user.which == 1%>
	<p> I am a Dog Owner!!!! I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!I am a Dog Owner!!!!</p>
	<h3> My Dogs:</h3>
	<div class="dog-box"><% @user.dogs.each do |dog| %>
		<div class="each-dog"><%= image_tag "dog.png", :style => "width:100px; height: 100px; opacity:.5;" %>
	  <%= link_to dog.name, dog_path(params[:id] = dog.id) %></div>
	<% end %>
</div>


<% else %>
	<p> I am a Dog Lover!!!! I don't own dogs. I want to play with yours!</p>
<% end %>

<% if @user == current_user %>
  <%= button_to "Add Dog", new_dog_path, :class => "button medium", :method => :get %>
<% end %>

</div>
</div>

	

<div class="send-message"><% if @user != current_user %>
	<h2> Send me a message to meet up! </h2>
	<%= simple_form_for Message.new do |f| %>
	  <%= f.hidden_field :to, :value => params[:id] %>
	  <%= f.hidden_field :date, :value => DateTime.now.to_date %>
	  <%= f.input :message %>
	  <%= f.button :submit %>
	<% end %>
<% end %>
</div>

</div>

app/views/visitors/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Bad+Script' rel='stylesheet' type='text/css'>


<div class="intro-pic"><div class="title animated fadeInDown" >Pawnder</div> 
<div class="descrip">"Like tinder, but for dogs"</div>
<div id="sign-up">
	<% if !user_signed_in? %>
	<button type="button" class="btn btn-primary"><%= link_to ' Sign up today!', new_user_session_path, :style => "color:#fff;"%></button>
	<% end %>
</div>
</div>



<div class="three-square">
	<div class="square">
		<%= image_tag "paw.png", :style => "width:150px; height: 150px; opacity:.5;" %>
	Blah blah blah Blah blah blah  Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah  </div>

	<div class="square">
		<%= image_tag "two_dogs.png", :style => "width:150px; height: 150px; opacity:.5;" %>
	Blah blah blah Blah blah blah  Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah  </div>

	<div class="square">
		<%= image_tag "walking.png", :style => "width:150px; height: 150px; opacity:.5;" %>
	Blah blah blah Blah blah blah  Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah Blah blah blah  </div>

</div>




<div class="users-reg"><%= link_to 'Users:', users_path %> <%= User.count %> registered</div>